name: Pull Repository to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIV_KEY }}

      - name: Add GitHub to known hosts
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Add server to known hosts
        run: echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Test SSH Connection to GitHub
        run: ssh -T git@github.com
        continue-on-error: true

      - name: Test SSH Connection to Server
        run: ssh -p 65002 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST 'echo "SSH connection successful"'
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_IP }}

      - name: Debug Information
        run: |
          echo 'Current directory: $(pwd)' &&
          echo 'Listing directory contents:' &&
          ls -al &&
          echo 'Git remotes:' &&
          git remote -v

      - name: Pull Repository
        run: |
          ssh -p 65002 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "
          ls &&
          cd ./domains/diekommunikatoere.de/public_html/hub/wp-content/plugins/dki_wiki_blocks &&
          if git remote | grep -q origin; then
            echo 'Remote origin exists, setting URL...'
            git remote set-url origin git@github.com:diekommunikatoere/dki_wiki_blocks.git
          else
            echo 'Remote origin does not exist, adding...'
            git remote add origin git@github.com:diekommunikatoere/dki_wiki_blocks.git
          fi &&
          echo 'Pulling from origin main...' &&
          git pull origin main "
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_IP }}
          SERVER_TARGET: ${{ secrets.TARGET }}
