name: Pull Repository to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIV_KEY }}

      - name: Add server to known hosts
        run: echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Pull Repository
        run: |
          ssh -p 65002 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "
          cd domains/diekommunikatoere.de/public_html/hub/wp-content/plugins/dki_wiki_blocks &&
          git init --initial-branch main &&
          git remote add origin git@github.com:diekommunikatoere/dki_wiki_blocks.git &&
          git pull origin "
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_IP }}
          SERVER_TARGET: ${{ secrets.TARGET }}
